version: '3.8'

services:
  # .NET API Service
  # dotnet_api:
  #   image: my-dotnet-api:latest    # Replace with your .NET API image name
  #   container_name: dotnet_api
  #   build:
  #     context: ./path/to/your/dotnet/api  # Replace with your .NET API project folder path
  #   ports:
  #     - "5000:80"   # Exposes port 80 from the container as port 5000 on your host
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development   # Set your environment variable if needed
  #     - ELASTICSEARCH_URL=http://elasticsearch:9200   # URL for the Elasticsearch service
  #   depends_on:
  #     - elasticsearch   # Ensures Elasticsearch is started before the API

  # Elasticsearch Service
  # elasticsearch:
  #   image: elasticsearch:7.17.0
  #   container_name: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - "9200:9200" # Exposes port 9200 from the container to port 9200 on the host
  #     - "9300:9300" # Port for internal communication (not usually needed for external access)
  #   ulimits:
  #     nproc: 65536
  #     nofile: 65536
  #   volumes:
  #     - esdata:/usr/share/elasticsearch/data # Named volume for Elasticsearch data
  #   networks:
  #     - backend

  # MogoDB Service
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017" # Map the host port 27017 to the container port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data1:/data/db1 # Persistent volume for MongoDB data   
  # Named volume for Elasticsearch data persistence
volumes:
  mongodb_data1:
  esdata:
    driver: local
  # Network for internal communication between containers
networks:
  backend:
    driver: bridge
